# Generated by Django 5.1.3 on 2025-01-20 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_model',
            name='hotel',
        ),
    ]
