# Generated by Django 5.1.3 on 2025-01-21 09:17

import django.db.models.deletion
import payments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_model_hotel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_model',
            old_name='create_time',
            new_name='payment_time',
        ),
        migrations.AlterField(
            model_name='payment_model',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[payments.models.positive_amount]),
        ),
        migrations.AlterField(
            model_name='payment_model',
            name='transaction_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='payment_model',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
