# Generated by Django 5.1.3 on 2025-01-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Bangladesh', max_length=100)),
                ('description', models.TextField()),
                ('amenities', models.TextField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_rooms', models.IntegerField()),
                ('available_rooms', models.IntegerField()),
                ('image', models.ImageField(upload_to='hotels/Image/')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
