# Generated by Django 5.1.3 on 2025-01-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_hotel_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_model',
            name='available_rooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='hotel_model',
            name='total_rooms',
            field=models.PositiveIntegerField(),
        ),
    ]
