# Generated by Django 5.1.3 on 2025-01-23 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotel_model_available_rooms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelImage_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/extra_images/')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.hotel_model')),
            ],
        ),
    ]
