# Generated by Django 5.1.3 on 2025-01-26 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_room_model_subtitle_room_model_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimage_model',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='hotels.room_model'),
        ),
    ]
