# Generated by Django 5.1.3 on 2025-02-02 19:15

import hotels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_alter_roomimage_model_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimage_model',
            name='image',
            field=models.ImageField(upload_to='hotels/extra_images/', validators=[hotels.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='room_model',
            name='bathrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room_model',
            name='bedrooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='room_model',
            name='beds',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='room_model',
            name='guests',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='roomimage_model',
            name='image',
            field=models.ImageField(upload_to='rooms/extra_images/', validators=[hotels.models.validate_image]),
        ),
    ]
