# Generated by Django 5.1.3 on 2025-02-03 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile_model',
            name='country',
        ),
    ]
