# Generated by Django 5.1.3 on 2025-02-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_model_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile_model',
            name='profile_image',
            field=models.ImageField(blank=True, default='accounts/default_profile.jpg', null=True, upload_to='accounts/profile_images/'),
        ),
    ]
