# Generated by Django 5.1.3 on 2025-02-20 15:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_model_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile_model',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='accounts/profile_images'),
        ),
    ]
