# Generated by Django 5.1.3 on 2025-01-24 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_alter_room_model_image'),
        ('reviews', '0002_alter_review_model_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review_model',
            options={'ordering': ['-create_time']},
        ),
        migrations.AlterUniqueTogether(
            name='review_model',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review_model',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_reviews', to='hotels.room_model'),
        ),
        migrations.AlterField(
            model_name='review_model',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_reviews', to='hotels.hotel_model'),
        ),
        migrations.AddConstraint(
            model_name='review_model',
            constraint=models.UniqueConstraint(fields=('user', 'hotel'), name='unique_hotel_review'),
        ),
        migrations.AddConstraint(
            model_name='review_model',
            constraint=models.UniqueConstraint(fields=('user', 'room'), name='unique_room_review'),
        ),
    ]
