# Generated by Django 5.1.3 on 2025-01-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_model',
            name='rooms_booked',
            field=models.PositiveIntegerField(),
        ),
    ]
