# Generated by Django 5.1.3 on 2025-01-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_model_rooms_booked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking_model',
            old_name='check_in',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='booking_model',
            old_name='check_out',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='booking_model',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='booking_model',
            name='total_nights',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
