# Generated by Django 5.1.3 on 2025-01-23 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_check_in_booking_model_end_date_and_more'),
        ('hotels', '0005_remove_hotel_model_available_rooms_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking_model',
            options={'ordering': ['-booking_time']},
        ),
        migrations.RenameField(
            model_name='booking_model',
            old_name='create_time',
            new_name='booking_time',
        ),
        migrations.RemoveField(
            model_name='booking_model',
            name='rooms_booked',
        ),
        migrations.AddField(
            model_name='booking_model',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking_model',
            name='guests',
            field=models.PositiveIntegerField(help_text='Number of guests (Max based on room capacity)', null=True),
        ),
        migrations.AddField(
            model_name='booking_model',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Payment transaction ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking_model',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotels.room_model'),
        ),
    ]
