# Generated by Django 5.1.3 on 2025-02-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_model_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_model',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
