# Generated by Django 5.1.3 on 2025-02-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_model_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_model',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
