# Generated by Django 5.1.3 on 2025-02-05 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_model_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_model',
            name='booking_status',
        ),
    ]
